name: Release

on:
  release:
    types: [published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build and prepare pnp-sass-importer project
        run: |
          yarn build
          cp README.md packages/pnp-sass-importer
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish
        working-directory: ./packages/pnp-sass-importer
